spring:
  application:
    name: vision
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:file:~/h2/vision/vision;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB          # 최대 파일 크기
      max-request-size: 50MB       # 최대 요청 크기
      file-size-threshold: 1MB     # 메모리에 저장될 임계 크기
  # 파일 업로드 설정 - `s3`
  cloud:
    aws:
      region:
        static: ap-northeast-2    # region
      credentials:
        access-key: YOUR_KEY
        secret-key: YOUR_SECRET
      s3:
        bucket: YOUR_BUCKET
        folder: YOUR_FOLDER
        domain: YOUR_DOMAIN  # s3 or cloudfront domain
  # 파일 업로드 설정 - `local`
  local:
    upload:
      path: ${user.home}/vision/upload
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
